[package]
name = "sundev/rojo-template"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[server-dependencies]
profileservice = "firebird702/profileservice@1.1.0"
cmdr = "evaera/cmdr@1.12.0"

[dependencies]
topbarplus = "1foreverhd/topbarplus@3.4.0"
promise = "evaera/promise@4.0.0"
typed-promise = "howmanysmall/typed-promise@4.0.3"
janitor = "howmanysmall/janitor@1.18.3"
replica = "ivasmigins/replica@0.1.0"
Signal = "sleitnick/signal@^1"
TableUtil = "sleitnick/table-util@^1"